package cli

// `secopsctl docs generate` — the generated command reference. Walks the same
// runnable-command tree as `commands` and writes one markdown page per
// top-level group into docs/commands/ plus an index, and syncs the
// marker-delimited block in docs/_sidebar.md — so the docs-site reference can
// never drift from the CLI. Hidden: a maintainer/CI tool, not an operator
// surface. `--check` regenerates in memory and fails when the committed files
// are stale (the CI freshness gate).

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func init() { rootCmd.AddCommand(newDocsCmd()) }

func newDocsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:    "docs",
		Short:  "Generate documentation and command-reference pages (maintainers)",
		Hidden: true,
	}
	cmd.AddCommand(newDocsGenerateCmd())
	requireSubcommand(cmd)
	return cmd
}

const (
	sidebarStartMarker = "<!-- commands:start -->"
	sidebarEndMarker   = "<!-- commands:end -->"
	generatedNotice    = "<!-- Generated by `secopsctl docs generate` — do not edit by hand. -->"
)

func newDocsGenerateCmd() *cobra.Command {
	var (
		outDir  string
		sidebar string
		check   bool
	)

	cmd := &cobra.Command{
		Use:   "generate",
		Short: "Generate the per-group command-reference pages under docs/commands/",
		Long: "Walk the command tree and write one markdown page per top-level command\n" +
			"group into docs/commands/ (plus an index README), and sync the\n" +
			"<!-- commands:start/end --> block in docs/_sidebar.md. With --check,\n" +
			"nothing is written: the run fails when any committed page, the index, or\n" +
			"the sidebar block is stale — the CI freshness gate.",
		Args: cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			pages := renderCommandPages(collectDocGroups())
			if check {
				return checkCommandDocs(pages, outDir, sidebar)
			}
			return writeCommandDocs(cmd, pages, outDir, sidebar)
		},
	}
	cmd.Flags().StringVar(&outDir, "out", "docs/commands", "output directory for the generated pages")
	cmd.Flags().StringVar(&sidebar, "sidebar", "docs/_sidebar.md", "sidebar file to sync (empty to skip)")
	cmd.Flags().BoolVar(&check, "check", false, "verify the committed pages are current; write nothing")
	return cmd
}

// docEntry is one runnable command with its full path (e.g. "soar case list").
type docEntry struct {
	path string
	cmd  *cobra.Command
}

// docGroup is one reference page: a top-level command group and its runnable
// commands. Single leaf top-level commands (doctor, drift, …) are folded into
// the synthetic "global" group.
type docGroup struct {
	name    string // top-level command name, or "global"
	short   string
	entries []docEntry
}

// collectDocGroups buckets every runnable command by its top-level segment.
// A top-level command with no runnable descendants lands in "global"; groups
// are sorted by name with "global" last.
func collectDocGroups() []docGroup {
	var entries []docEntry
	walkRunnable(rootCmd, "", func(path string, c *cobra.Command) {
		entries = append(entries, docEntry{path: path, cmd: c})
	})
	sort.Slice(entries, func(i, j int) bool { return entries[i].path < entries[j].path })

	shortByName := make(map[string]string)
	for _, c := range rootCmd.Commands() {
		shortByName[c.Name()] = c.Short
	}

	byTop := make(map[string][]docEntry)
	for _, e := range entries {
		top, _, _ := strings.Cut(e.path, " ")
		byTop[top] = append(byTop[top], e)
	}

	var groups []docGroup
	var global docGroup
	for top, es := range byTop {
		// A single entry whose path IS the top-level name is a plain leaf
		// command (doctor, drift, pull, …) — folded into "global".
		if len(es) == 1 && es[0].path == top {
			global.entries = append(global.entries, es[0])
			continue
		}
		groups = append(groups, docGroup{name: top, short: shortByName[top], entries: es})
	}
	sort.Slice(groups, func(i, j int) bool { return groups[i].name < groups[j].name })
	if len(global.entries) > 0 {
		sort.Slice(global.entries, func(i, j int) bool { return global.entries[i].path < global.entries[j].path })
		global.name, global.short = "global", "Top-level commands"
		groups = append(groups, global)
	}
	return groups
}

// renderCommandPages renders every group page plus the index, keyed by
// filename (relative to the output directory).
func renderCommandPages(groups []docGroup) map[string]string {
	pages := make(map[string]string, len(groups)+1)
	for _, g := range groups {
		pages[g.name+".md"] = renderCommandGroup(g)
	}
	pages["README.md"] = renderCommandIndex(groups)
	return pages
}

func renderCommandGroup(g docGroup) string {
	var b strings.Builder
	b.WriteString(generatedNotice + "\n\n")
	if g.name == "global" {
		b.WriteString("# Global commands\n\n")
	} else {
		fmt.Fprintf(&b, "# secopsctl %s\n\n", g.name)
	}
	if g.short != "" {
		b.WriteString(g.short + "\n")
	}
	for _, e := range g.entries {
		b.WriteString("\n")
		renderCommandEntry(&b, e)
	}
	return b.String()
}

func renderCommandEntry(b *strings.Builder, e docEntry) {
	fmt.Fprintf(b, "## %s\n\n", e.path)
	if e.cmd.Short != "" {
		b.WriteString(e.cmd.Short + "\n\n")
	}
	if commandKind(e.cmd) == "guarded-mutation" {
		b.WriteString("> Guarded mutation — dry-run by default; apply with `--yes`.\n\n")
	}
	fmt.Fprintf(b, "```text\n%s\n```\n", e.cmd.UseLine())

	// The Long help is CLI help text, not authored markdown — fence it verbatim
	// so stray tables/lists/pipes inside it can never break the page.
	if long := strings.TrimSpace(e.cmd.Long); long != "" && long != e.cmd.Short {
		fence := "```"
		if strings.Contains(long, "```") {
			fence = "~~~~"
		}
		fmt.Fprintf(b, "\n%stext\n%s\n%s\n", fence, long, fence)
	}

	if rows := flagTableRows(e.cmd); len(rows) > 0 {
		b.WriteString("\n**Flags**\n\n")
		b.WriteString("| Flag | Type | Default | Description |\n")
		b.WriteString("|---|---|---|---|\n")
		for _, r := range rows {
			b.WriteString(r + "\n")
		}
	}

	if ex := strings.TrimSpace(e.cmd.Example); ex != "" {
		fmt.Fprintf(b, "\n**Examples**\n\n```bash\n%s\n```\n", ex)
	}
}

// flagTableRows renders the command's own flags as markdown table rows.
func flagTableRows(c *cobra.Command) []string {
	var rows []string
	c.LocalFlags().VisitAll(func(f *pflag.Flag) {
		if f.Hidden || f.Name == "help" {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		def := f.DefValue
		if def == "" || def == "[]" {
			def = "-"
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | %s | %s |",
			tableCell(name), tableCell(f.Value.Type()), tableCell(def), tableCell(f.Usage)))
	})
	return rows
}

// tableCell makes an arbitrary string safe inside a one-line markdown table
// cell: pipes are escaped and newlines collapse to spaces.
func tableCell(s string) string {
	s = strings.ReplaceAll(s, "|", `\|`)
	s = strings.Join(strings.Fields(s), " ")
	return s
}

func renderCommandIndex(groups []docGroup) string {
	var b strings.Builder
	b.WriteString(generatedNotice + "\n\n")
	b.WriteString("# Command reference\n\n")
	b.WriteString("Generated from the command tree — run `go run ./cmd/secopsctl docs generate`\n")
	b.WriteString("after changing a command. \"Guarded\" commands are live mutations behind the\n")
	b.WriteString("standard `--dry-run`/`--yes` gate; everything else is a read.\n\n")
	b.WriteString("| Group | Commands | Description |\n")
	b.WriteString("|---|---|---|\n")
	for _, g := range groups {
		fmt.Fprintf(&b, "| [%s](%s.md) | %d | %s |\n",
			g.name, g.name, len(g.entries), tableCell(g.short))
	}
	return b.String()
}

// renderSidebarBlock renders the marker-delimited command-reference section for
// docs/_sidebar.md.
func renderSidebarBlock(pages map[string]string) string {
	names := make([]string, 0, len(pages))
	for f := range pages {
		if f != "README.md" {
			names = append(names, strings.TrimSuffix(f, ".md"))
		}
	}
	sort.Strings(names)
	var b strings.Builder
	b.WriteString(sidebarStartMarker + "\n")
	b.WriteString("- **Command reference**\n")
	b.WriteString("  - [Overview](commands/README.md)\n")
	for _, n := range names {
		fmt.Fprintf(&b, "  - [%s](commands/%s.md)\n", n, n)
	}
	b.WriteString(sidebarEndMarker)
	return b.String()
}

// patchSidebar replaces the marker-delimited block in the sidebar content, or
// inserts one before the "- **Design**" section on first run.
func patchSidebar(content, block string) (string, error) {
	if start := strings.Index(content, sidebarStartMarker); start >= 0 {
		end := strings.Index(content, sidebarEndMarker)
		if end < start {
			return "", fmt.Errorf("sidebar: %s found without a following %s", sidebarStartMarker, sidebarEndMarker)
		}
		return content[:start] + block + content[end+len(sidebarEndMarker):], nil
	}
	anchor := "- **Design**"
	if i := strings.Index(content, anchor); i >= 0 {
		return content[:i] + block + "\n\n" + content[i:], nil
	}
	return strings.TrimRight(content, "\n") + "\n\n" + block + "\n", nil
}

func writeCommandDocs(cmd *cobra.Command, pages map[string]string, outDir, sidebar string) error {
	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return err
	}
	for name, content := range pages {
		if err := os.WriteFile(filepath.Join(outDir, name), []byte(content), 0o644); err != nil { //nolint:gosec // public docs
			return err
		}
	}
	stale, err := staleCommandPages(pages, outDir)
	if err != nil {
		return err
	}
	for _, f := range stale {
		if err := os.Remove(filepath.Join(outDir, f)); err != nil {
			return err
		}
	}
	if sidebar != "" {
		if err := syncSidebar(pages, sidebar); err != nil {
			return err
		}
	}
	fmt.Fprintf(cmd.OutOrStdout(), "generated %d page(s) in %s", len(pages), outDir)
	if len(stale) > 0 {
		fmt.Fprintf(cmd.OutOrStdout(), ", removed %d stale", len(stale))
	}
	fmt.Fprintln(cmd.OutOrStdout())
	return nil
}

func syncSidebar(pages map[string]string, sidebar string) error {
	raw, err := os.ReadFile(sidebar) //nolint:gosec // maintainer-supplied path
	if err != nil {
		return err
	}
	patched, err := patchSidebar(string(raw), renderSidebarBlock(pages))
	if err != nil {
		return err
	}
	if patched == string(raw) {
		return nil
	}
	return os.WriteFile(sidebar, []byte(patched), 0o644) //nolint:gosec // public docs
}

// staleCommandPages lists committed *.md files in outDir that the current
// command tree no longer generates (e.g. a renamed group).
func staleCommandPages(pages map[string]string, outDir string) ([]string, error) {
	dirents, err := os.ReadDir(outDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, err
	}
	var stale []string
	for _, d := range dirents {
		name := d.Name()
		if d.IsDir() || !strings.HasSuffix(name, ".md") {
			continue
		}
		if _, ok := pages[name]; !ok {
			stale = append(stale, name)
		}
	}
	sort.Strings(stale)
	return stale, nil
}

func checkCommandDocs(pages map[string]string, outDir, sidebar string) error {
	var problems []string
	for name, content := range pages {
		disk, err := os.ReadFile(filepath.Join(outDir, name)) //nolint:gosec // repo-relative docs path
		switch {
		case os.IsNotExist(err):
			problems = append(problems, "missing: "+name)
		case err != nil:
			return err
		case string(disk) != content:
			problems = append(problems, "stale: "+name)
		}
	}
	stale, err := staleCommandPages(pages, outDir)
	if err != nil {
		return err
	}
	for _, f := range stale {
		problems = append(problems, "orphaned: "+f)
	}
	if sidebar != "" {
		raw, err := os.ReadFile(sidebar) //nolint:gosec // maintainer-supplied path
		if err != nil {
			return err
		}
		patched, err := patchSidebar(string(raw), renderSidebarBlock(pages))
		if err != nil {
			return err
		}
		if patched != string(raw) {
			problems = append(problems, "stale: "+sidebar+" command-reference block")
		}
	}
	if len(problems) > 0 {
		sort.Strings(problems)
		return fmt.Errorf("command reference is out of date — run `go run ./cmd/secopsctl docs generate`:\n  %s",
			strings.Join(problems, "\n  "))
	}
	return nil
}
